name: Build & Test w/ df-redis replica

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Build the Docker image
      uses: actions/checkout@v3
    -
      name: Build host info
      run: |
        uname -a
        cat /etc/os-release
    -
      name: Build all images for test
      run: |
        docker-compose -f docker-compose-replica-dragonfly.yaml build
    -
      name: Run test
      run: |
        bash -c " \
        docker-compose -f docker-compose-replica-dragonfly.yaml up -d redis-primary redis-replica redis-acl-helper \
        && docker-compose -f docker-compose-replica-dragonfly.yaml up --abort-on-container-exit --exit-code-from=python-test python-test"
